config/routes.rb
Rails.application.routes.draw do
  root 'states#index'
  devise_for :users
  resources :states
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/state.rb
class State < ApplicationRecord
  validates :name, presence: true
  validates :capital, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    @state.save
    redirect_to states_path
  end

  def edit
    @state = State.find(params[:id])
  end

  def update
    @state = State.find(params[:id])
    @state.update!(state_params)
    redirect_to root_path
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy
    redirect_to root_path
  end

  private

  def state_params
    params.require(:state).permit(:name, :capital)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Geography Updated Exercise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all' %>
      <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Basic Geography Exercise</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <%- if current_user -%>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
        </ul>
      </section>
    </nav>

    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>
  </body>
</html>

app/views/states/edit.html.erb
<h1>Edit State Details Form</h1>
  <%= form_for @state do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :capital %>
  <%= f.text_field :capital %>
  <%= f.submit %>
<% end %>

app/views/states/index.html.erb
<h1> States List </h1>
<%= link_to 'Add New', new_state_path(@state) %>
<% @states.each do |state| %>
  <li><%= "The capital of #{state.name} is #{state.capital}" %>
    <%= link_to 'Edit', edit_state_path(state) %> | <%= link_to 'Delete', state, method: :delete,
    data: { confirm: 'Are you sure u wanna delete dis thang?' } %>
  </li>
<% end %>

app/views/states/new.html.erb
<h1>New State Details Form</h1>
  <%= form_for @state do |f| %>
  <%= f.label :state %>
  <%= f.text_field :name %>
  <%= f.label :capital %>
  <%= f.text_field :capital %>
  <%= f.submit %>
<% end %>